### PR TITLE
fix: make search filter accent-insensitive

### LINKED ISSUE #33: [bug] filtering should not be accent sensitive
Any filtering should ignore any kind of diacritics, i.e.: if user searches for `farmacia` he should get results of merchants named `farmácia`

Supposedly this snipet normalizes any string to remove these things

```dart
String normalizeString(String input) {
  // Normalize to NFD (Normalization Form Decomposition)
  String normalized = input.characters.toList().map((char) {
    var bytes = utf8.encode(char);
    var decoded = utf8.decode(bytes);
    return decoded;
  }).join();

  // Remove diacritics by replacing them with their base characters
  // This uses a regex to match all combining diacritical marks
  return normalized.replaceAll(RegExp(r'[\u0300-\u036f]'), '');
}
```

https://chatgpt.com/share/68404a73-f900-8007-be05-0b6cb91ee1e2

### PR DESCRIPTION
**Pull request by valkopt00**
filtering issue where user search queries were being matched strictly and failed to account for accented characters.

Example: Searching for farmacia would not match farmácia.

Introduced the diacritics package to normalize both the search query and the data being filtered.

Applied accent-insensitive filtering to:
- Merchant names
- Card names and their associated Merchant names

Closes #33

### CODE REVIEW

File: lib/src/screens/add_card/select_merchant_screen.dart [hunk 1]
```diff
@@ -53,10 +51,15 @@ class _SelectMerchantScreenState extends State<SelectMerchantScreen> {
...
             // Filter merchants based on search query
-            final filteredMerchants =
-            _searchQuery.isEmpty
+            final queryNormalized = removeDiacritics(_searchQuery.toLowerCase());
+
+            final filteredMerchants = _searchQuery.isEmpty
                 ? merchants
-                : merchants.where((merchant) => merchant.displayName.toLowerCase().contains(_searchQuery)).toList();
+                : merchants.where((merchant) {
+              final nameNormalized = removeDiacritics(merchant.displayName.toLowerCase());
```
Comment (Ribeiro-Tiago) [inline lib/src/screens/add_card/select_merchant_screen.dart:59]: aqui não tem direito a pesquisar pelo name? só displayName? xD

File: lib/src/screens/add_card/select_merchant_screen.dart [hunk 2]
```diff
@@ -53,10 +51,15 @@ class _SelectMerchantScreenState extends State<SelectMerchantScreen> {
...
+              return nameNormalized.contains(queryNormalized);
```
Comment (Ribeiro-Tiago) [inline lib/src/screens/add_card/select_merchant_screen.dart:60]: variaveis desnecessárias :p 

pode ser só 

```suggestion
              return removeDiacritics(merchant.displayName.toLowerCase()).contains(queryNormalized);
```

**Review by Ribeiro-Tiago — APPROVED** [review]
